title: Mark Eagle # your name (or website title) here
logo: "https://github.com/chereagle1/chereagle1.github.io/blob/master/main%20pic.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced GIS Professional 
  <br><br>
  U.S. Army Veteran and 
  Experienced Defense Contractor 
  <br><br>
  <a href="www.linkedin.com/in/mark-eagle-61787a187">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
